const PARTS_CATALOG = [
  // Front End
  { cat: "Front End", name: "Hood", op: "refinish" },
  { cat: "Front End", name: "Hood Hinge", op: "replace" },
  { cat: "Front End", name: "Hood Latch", op: "replace" },
  { cat: "Front End", name: "Hood Hinge Reinforcement", op: "replace" },
  { cat: "Front End", name: "Hood Ornament", op: "replace" },
  { cat: "Front End", name: "Bumper Assembly", op: "replace" },
  { cat: "Front End", name: "Bumper Cover", op: "refinish" },
  { cat: "Front End", name: "Bumper Reinforcement", op: "replace" },
  { cat: "Front End", name: "Bumper Valance Panel", op: "refinish" },
  { cat: "Front End", name: "Bumper Grille", op: "replace" },
  { cat: "Front End", name: "Grille Assembly", op: "replace" },
  { cat: "Front End", name: "Grille Emblem", op: "replace" },
  { cat: "Front End", name: "Fender", op: "refinish" },
  { cat: "Front End", name: "Fender Flare", op: "replace" },
  { cat: "Front End", name: "Fender Liner", op: "replace" },
  { cat: "Front End", name: "Fender Moulding", op: "replace" },
  { cat: "Front End", name: "Fender Reinforcement", op: "replace" },
  { cat: "Front End", name: "Apron", op: "replace" },
  { cat: "Front End", name: "Apron Reinforcement", op: "replace" },
  { cat: "Front End", name: "Headlamp Assembly", op: "replace" },
  { cat: "Front End", name: "Headlamp Housing", op: "replace" },
  { cat: "Front End", name: "Headlamp Finisher", op: "replace" },
  { cat: "Front End", name: "Headlamp Filler", op: "replace" },
  { cat: "Front End", name: "Headlamp Bezel", op: "replace" },
  { cat: "Front End", name: "Headlamp Door", op: "replace" },
  { cat: "Front End", name: "Valance Panel", op: "refinish" },
  { cat: "Front End", name: "Header Panel", op: "replace" },
  { cat: "Front End", name: "Header Panel Moulding", op: "replace" },
  { cat: "Front End", name: "Cowl Panel", op: "replace" },
  { cat: "Front End", name: "Cowl Grille Panel", op: "replace" },

  // Doors
  { cat: "Doors", name: "Door Shell", op: "replace" },
  { cat: "Doors", name: "Door Assy", op: "R&I" },
  { cat: "Doors", name: "Door Skin", op: "refinish" },
  { cat: "Doors", name: "Door Outer Panel", op: "replace" },
  { cat: "Doors", name: "Door Inner Panel", op: "replace" },
  { cat: "Doors", name: "Door Frame", op: "replace" },
  { cat: "Doors", name: "Door Hinge", op: "replace" },
  { cat: "Doors", name: "Door Latch", op: "replace" },
  { cat: "Doors", name: "Door Strike", op: "replace" },
  { cat: "Doors", name: "Door Handle", op: "replace" },
  { cat: "Doors", name: "Door Handle Outer", op: "replace" },
  { cat: "Doors", name: "Door Handle Inner", op: "replace" },
  { cat: "Doors", name: "Door Mirror", op: "replace" },
  { cat: "Doors", name: "Door Mirror Glass", op: "replace" },
  { cat: "Doors", name: "Door Mirror Housing", op: "replace" },
  { cat: "Doors", name: "Door Mirror Moulding", op: "replace" },
  { cat: "Doors", name: "Door Glass", op: "replace" },
  { cat: "Doors", name: "Door Glass Regulator", op: "replace" },
  { cat: "Doors", name: "Door Glass Run", op: "replace" },
  { cat: "Doors", name: "Door Weatherstrip", op: "replace" },
  { cat: "Doors", name: "Door Trim Panel", op: "replace" },
  { cat: "Doors", name: "Door Belt Moulding", op: "replace" },
  { cat: "Doors", name: "Door Lower Moulding", op: "replace" },
  { cat: "Doors", name: "Door Moulding", op: "replace" },
  { cat: "Doors", name: "Door Edge Guard", op: "replace" },
  { cat: "Doors", name: "Door Reinforcement", op: "replace" },
  { cat: "Doors", name: "Door Gasket", op: "replace" },

  // Rear End
  { cat: "Rear End", name: "Tailgate", op: "refinish" },
  { cat: "Rear End", name: "Tailgate Assembly", op: "replace" },
  { cat: "Rear End", name: "Tailgate Handle", op: "replace" },
  { cat: "Rear End", name: "Tailgate Moulding", op: "replace" },
  { cat: "Rear End", name: "Tailgate Spoiler", op: "replace" },
  { cat: "Rear End", name: "Deck Lid", op: "refinish" },
  { cat: "Rear End", name: "Deck Lid Hinge", op: "replace" },
  { cat: "Rear End", name: "Deck Lid Latch", op: "replace" },
  { cat: "Rear End", name: "Deck Lid Moulding", op: "replace" },
  { cat: "Rear End", name: "Rear Bumper", op: "replace" },
  { cat: "Rear End", name: "Rear Bumper Cover", op: "refinish" },
  { cat: "Rear End", name: "Rear Bumper Reinforcement", op: "replace" },
  { cat: "Rear End", name: "Rear Bumper Valance", op: "refinish" },
  { cat: "Rear End", name: "Tail Lamp Assembly", op: "replace" },
  { cat: "Rear End", name: "Tail Lamp Housing", op: "replace" },
  { cat: "Rear End", name: "Backup Lamp", op: "replace" },
  { cat: "Rear End", name: "License Plate Panel", op: "refinish" },
  { cat: "Rear End", name: "License Plate Housing", op: "replace" },

  // Roof & Top
  { cat: "Roof/Top", name: "Roof Panel", op: "refinish" },
  { cat: "Roof/Top", name: "Roof Rail", op: "replace" },
  { cat: "Roof/Top", name: "Roof Rack", op: "replace" },
  { cat: "Roof/Top", name: "Sunroof Panel", op: "replace" },
  { cat: "Roof/Top", name: "Sunroof Motor", op: "replace" },
  { cat: "Roof/Top", name: "Headliner", op: "replace" },
  { cat: "Roof/Top", name: "Header Panel", op: "replace" },
  { cat: "Roof/Top", name: "Drip Rail", op: "replace" },
  { cat: "Roof/Top", name: "Roof Moulding", op: "replace" },
  { cat: "Roof/Top", name: "Roof Weatherstrip", op: "replace" },

  // Side & Quarter
  { cat: "Side/Quarter", name: "Quarter Panel", op: "refinish" },
  { cat: "Side/Quarter", name: "Quarter Panel Assembly", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Panel Outer", op: "refinish" },
  { cat: "Side/Quarter", name: "Quarter Panel Inner", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Panel Upper", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Panel Lower", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Moulding", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Belt Moulding", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Trim Panel", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Pillar", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Glass", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Window", op: "replace" },
  { cat: "Side/Quarter", name: "Quarter Drip Moulding", op: "replace" },
  { cat: "Side/Quarter", name: "Rocker Panel", op: "refinish" },
  { cat: "Side/Quarter", name: "Rocker Panel Assembly", op: "replace" },
  { cat: "Side/Quarter", name: "Rocker Moulding", op: "replace" },
  { cat: "Side/Quarter", name: "Rocker Trim Panel", op: "replace" },
  { cat: "Side/Quarter", name: "Rocker Reinforcement", op: "replace" },
  { cat: "Side/Quarter", name: "Rocker Filler", op: "replace" },
  { cat: "Side/Quarter", name: "Body Side Molding", op: "replace" },
  { cat: "Side/Quarter", name: "Bedside Panel", op: "refinish" },
  { cat: "Side/Quarter", name: "Bedside Fender", op: "replace" },
  { cat: "Side/Quarter", name: "Pillar", op: "replace" },
  { cat: "Side/Quarter", name: "Hinge Pillar", op: "replace" },
  { cat: "Side/Quarter", name: "Hinge Pillar Reinforcement", op: "replace" },
  { cat: "Side/Quarter", name: "Center Pillar", op: "replace" },

  // Glass
  { cat: "Glass", name: "Windshield", op: "replace" },
  { cat: "Glass", name: "Windshield Moulding", op: "replace" },
  { cat: "Glass", name: "Windshield Weatherstrip", op: "replace" },
  { cat: "Glass", name: "Windshield Pillar", op: "replace" },
  { cat: "Glass", name: "Back Glass", op: "replace" },
  { cat: "Glass", name: "Back Window Moulding", op: "replace" },
  { cat: "Glass", name: "Back Window Weatherstrip", op: "replace" },
  { cat: "Glass", name: "Door Glass", op: "replace" },
  { cat: "Glass", name: "Quarter Glass", op: "replace" },
  { cat: "Glass", name: "Quarter Window", op: "replace" },
  { cat: "Glass", name: "Vent Glass", op: "replace" },
  { cat: "Glass", name: "Door Window Frame", op: "replace" },
  { cat: "Glass", name: "Quarter Window Frame", op: "replace" },
  { cat: "Glass", name: "Glass Clips", op: "replace" },
  { cat: "Glass", name: "Glass Weatherstrip", op: "replace" },

  // Frame & Structure
  { cat: "Frame/Structure", name: "Frame Rail", op: "replace" },
  { cat: "Frame/Structure", name: "Frame Side Rail", op: "replace" },
  { cat: "Frame/Structure", name: "Frame Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Crossmember", op: "replace" },
  { cat: "Frame/Structure", name: "Crossmember Assembly", op: "replace" },
  { cat: "Frame/Structure", name: "Crossmember Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Front Axle Support", op: "replace" },
  { cat: "Frame/Structure", name: "Rear Axle Support", op: "replace" },
  { cat: "Frame/Structure", name: "Apron", op: "replace" },
  { cat: "Frame/Structure", name: "Apron Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Cowl", op: "replace" },
  { cat: "Frame/Structure", name: "Cowl Side Panel", op: "replace" },
  { cat: "Frame/Structure", name: "Cowl Side Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Cowl Top Panel", op: "replace" },
  { cat: "Frame/Structure", name: "Floor Pan", op: "replace" },
  { cat: "Frame/Structure", name: "Floor Pan Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Radiator Support", op: "replace" },
  { cat: "Frame/Structure", name: "Radiator Support Reinforcement", op: "replace" },
  { cat: "Frame/Structure", name: "Engine Compartment Panel", op: "replace" },

  // Cab (Trucks)
  { cat: "Cab", name: "Cab Shell", op: "replace" },
  { cat: "Cab", name: "Cab Assembly", op: "replace" },
  { cat: "Cab", name: "Cab Roof", op: "replace" },
  { cat: "Cab", name: "Cab Roof Moulding", op: "replace" },
  { cat: "Cab", name: "Cab Back Panel", op: "refinish" },
  { cat: "Cab", name: "Cab Corner Panel", op: "replace" },
  { cat: "Cab", name: "Cab Door", op: "refinish" },
  { cat: "Cab", name: "Cab Hinge Pillar", op: "replace" },
  { cat: "Cab", name: "Cab Pillar", op: "replace" },
  { cat: "Cab", name: "Cab Side Panel", op: "refinish" },
  { cat: "Cab", name: "Cab Rocker Panel", op: "refinish" },
  { cat: "Cab", name: "Cab Sunroof", op: "replace" },
  { cat: "Cab", name: "Cab Headliner", op: "replace" },

  // Trim & Moulding
  { cat: "Trim/Moulding", name: "Door Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Door Belt Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Door Lower Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Window Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Windshield Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Back Window Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Hood Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Fender Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Rocker Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Quarter Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Roof Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Bumper Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Trim Panel", op: "replace" },
  { cat: "Trim/Moulding", name: "Door Trim Panel", op: "replace" },
  { cat: "Trim/Moulding", name: "Rocker Trim Panel", op: "replace" },
  { cat: "Trim/Moulding", name: "Trim Panel Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Emblem", op: "replace" },
  { cat: "Trim/Moulding", name: "Emblem Badge", op: "replace" },
  { cat: "Trim/Moulding", name: "Door Handle Trim", op: "replace" },
  { cat: "Trim/Moulding", name: "Cowl Trim Panel", op: "replace" },
  { cat: "Trim/Moulding", name: "Headlamp Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Deck Lid Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Tailgate Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Body Side Molding", op: "replace" },
  { cat: "Trim/Moulding", name: "Running Board", op: "replace" },
  { cat: "Trim/Moulding", name: "Running Board Moulding", op: "replace" },
  { cat: "Trim/Moulding", name: "Splash Shield", op: "replace" },
  { cat: "Trim/Moulding", name: "Splash Guard", op: "replace" },
  { cat: "Trim/Moulding", name: "Mud Flap", op: "replace" },

  // Lighting
  { cat: "Lighting", name: "Headlamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Headlamp Housing", op: "replace" },
  { cat: "Lighting", name: "Headlamp Bezel", op: "replace" },
  { cat: "Lighting", name: "Headlamp Door", op: "replace" },
  { cat: "Lighting", name: "Headlamp Finisher", op: "replace" },
  { cat: "Lighting", name: "Headlamp Filler", op: "replace" },
  { cat: "Lighting", name: "Tail Lamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Tail Lamp Housing", op: "replace" },
  { cat: "Lighting", name: "Tail Lamp Lens", op: "replace" },
  { cat: "Lighting", name: "Marker Lamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Marker Lamp Housing", op: "replace" },
  { cat: "Lighting", name: "Backup Lamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Backup Lamp Housing", op: "replace" },
  { cat: "Lighting", name: "Signal Lamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Signal Lamp Housing", op: "replace" },
  { cat: "Lighting", name: "Fog Lamp Assembly", op: "replace" },
  { cat: "Lighting", name: "Fog Lamp Housing", op: "replace" },
  { cat: "Lighting", name: "Reflector", op: "replace" },
  { cat: "Lighting", name: "Side Marker Assembly", op: "replace" },

  // Mechanical (paint/body shop relevant only)
  { cat: "Mechanical", name: "Radiator", op: "replace" },
  { cat: "Mechanical", name: "Radiator Support", op: "replace" },
  { cat: "Mechanical", name: "Radiator Shroud", op: "replace" },
  { cat: "Mechanical", name: "Condenser", op: "replace" },
  { cat: "Mechanical", name: "Condenser Shroud", op: "replace" },
  { cat: "Mechanical", name: "Wiper Motor", op: "replace" },
  { cat: "Mechanical", name: "Wiper Blade Assembly", op: "replace" },
  { cat: "Mechanical", name: "Wiper Arm", op: "replace" },
  { cat: "Mechanical", name: "Wiper Transmission Assembly", op: "replace" },
  { cat: "Mechanical", name: "Washer Fluid Reservoir", op: "replace" },
  { cat: "Mechanical", name: "Door Mirror Motor", op: "replace" },
  { cat: "Mechanical", name: "Door Window Regulator", op: "replace" },
  { cat: "Mechanical", name: "Exhaust System", op: "replace" },
  { cat: "Mechanical", name: "Muffler", op: "replace" },
  { cat: "Mechanical", name: "Fuel Door", op: "replace" },
  { cat: "Mechanical", name: "Fuel Door Hinge", op: "replace" },
];
